version: '3.7'

services:
  esphome:
    image: esphome/esphome
    container_name: esphome
    volumes:
      - ./esphome:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: /config dashboard --username USER --password PASSWORD
