###############
substitutions:
    devicename: "m5stickwhg1eingang"
    upper_devicename: M5STICKC
    friendly_name: whg1_RFID_Eingangskontrolle
    device_description: RFID Eingangskontrolle
    mqtt_prefix: ESPhome_M5STICKC_Whg1_Eingangskontrolle
  ##############
  
  
esphome:
    name: $devicename
    comment: ${device_description}
    platform: ESP32
    board: m5stick-c
    includes:
    - custom_components/axp192/axp192.h

#external_components:
#  - source:
#      type: git
#      url: https://github.com/ssieb/custom_components
#    components: [ ip5306 ]
  
external_components: #include homething, and esphome-components
  - source:
      type: git
      url: https://gitlab.com/geiseri/esphome_extras.git
      #url: https://github.com/landonr/esphome-axp192
      #ref: "lando/add-charging-indicator"
    refresh: 0s
    components: [axp192]

  #packages: # These allow merging whereas global includes do not
  #  common_sensors: !include /config/esphome/custom_components/common_sensors.yaml # Includes number, text and binary
  
  
  # Enable logging
logger:
    level: debug
  
web_server: 
    port: 80
  
time:
    - platform: sntp
      id: sntp_time
      timezone: Europe/Berlin
  
sun: # https://esphome.io/components/sun.html
    latitude: 52.383124 
    longitude: 13.421259
  
    on_sunrise:
      - then:
          - logger.log: Good morning!
      # Custom elevation, will be called shortly after the trigger above.
      - elevation: 5°
        then:
          - logger.log: Good morning 2!
  
    on_sunset:
      - then:
          - logger.log: Good evening!
  
# Enable Home Assistant API
api:
    encryption:
      key: !secret api_password

ota:
    password: !secret ota_password
  
wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    fast_connect: true
    id: wifi_id
    power_save_mode: HIGH
  
    ap:
      ssid: "M5Stack-Core2 Fallback Hotspot"
      password: "cjjnAykk8TbE"
  
    manual_ip:
      static_ip: 192.168.1.42
      gateway: 192.168.1.1
      subnet: 255.255.255.0
  
captive_portal:
  
mqtt:
  broker: !secret mqtt_ip
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: $devicename
  
  birth_message:
     topic: $mqtt_prefix
     payload: Online
     retain: true
  
  will_message:
      topic: $mqtt_prefix
      payload: Offline
      retain: true
  
  shutdown_message:
     topic: $mqtt_prefix
     payload: Shutdown
     retain: true

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

esp32_touch:
  #setup_mode: true
  iir_filter: 10ms

axp192: # setup backlight and charging
 id: axp
 address: 0x34
 update_interval: 60s
 charge_voltage: 4150mV
 dcdc1_voltage: 3300mv
 dcdc3_voltage: 1.5V
 i2c_id: bus_a

#globals: 
#  - id: charging
#    type: bool
#    restore_value: no
#    initial_value: "false"

sensor: # AXP192 power management - must be present to initialize TFT power on
  - platform: axp192
    axp192_id: axp
    id: batteryPercent
    type: battery_power

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    internal: True
    
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal %"
    id: wifi_signal_percent
    internal: True
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
  
    # Uptime sensor.
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 10s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      internal: True
      id: wifi_ip
    ssid:
      name: SSID
      internal: True
      id: wifi_ssid

output:
 - platform: ledc
   pin: 10
   inverted: true
   id: builtin_led
 - platform: axp192
   axp192_id: axp
   output: ldo3
   id: axp_ldo3

#G4=IR
remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

# internal LED
light: # internal LED
 - platform: monochromatic
   output:  builtin_led
   name: Led
   id: led1
   internal: True
 - platform: monochromatic
   output: axp_ldo3
   restore_mode: ALWAYS_ON
   name: "Backlight"
   id: backlight
   internal: True

binary_sensor:
  - platform: axp192
    axp192_id: axp
    type: charge_indicate
    id: axp_charger
    name: "Charger"
    on_state:
      then:
        lambda: |-
         //  charging = x;
  - platform: status
    id: api_connected
    internal: true
  # Button A implementation
  - platform: gpio
    name: Button
    pin:
      number: GPIO37
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed

switch:
  - platform: axp192
    axp192_id: axp
    output: ldo3
    name: LDO3
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"
        

font:
  - file: "fonts/OpenSans-Regular.ttf"
    id: font1
    size: 66

color:
    - id: color_wet
      red: 100%
      green: 0%
      blue: 0%
    - id: color_dry
      red: 0%
      green: 100%
      blue: 0%

# built-in 80x160 TFT
display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    rotation: 0
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    update_interval: 60s
    lambda: |
        it.print(42, -24, id(font1), id(color_wet), TextAlign::TOP_CENTER, "W");
        it.print(42, 32, id(font1), id(color_wet), TextAlign::TOP_CENTER, "E");
        it.print(42, 85, id(font1), id(color_wet), TextAlign::TOP_CENTER, "T");