###############
substitutions:
    devicename: "m5stickwhg1eingang"
    upper_devicename: M5STICKC
    friendly_name: whg1_RFID_Eingangskontrolle
    device_description: RFID Eingangskontrolle
    mqtt_prefix: ESPhome_M5STICKC_Whg1_Eingangskontrolle
  ##############

  
  
esphome:
    name: $devicename
    comment: ${device_description}
    platform: ESP32
    board: m5stick-c
#    includes:
  
logger:
    level: debug
  
web_server: 
    port: 80
  
time:
    - platform: sntp
      id: sntp_time
      timezone: Europe/Berlin
  
sun: # https://esphome.io/components/sun.html
    latitude: 52.383124 
    longitude: 13.421259
  
    on_sunrise:
      - then:
          - logger.log: Good morning!
      # Custom elevation, will be called shortly after the trigger above.
      - elevation: 5°
        then:
          - logger.log: Good morning 2!
  
    on_sunset:
      - then:
          - logger.log: Good evening!
  